Class {
	#name : 'MyOffBoardSquare',
	#superclass : 'Object',
	#category : 'Myg-Chess-Core',
	#package : 'Myg-Chess-Core'
}

{ #category : 'accessing' }
MyOffBoardSquare >> contents [

	^ nil
]

{ #category : 'as yet unclassified' }
MyOffBoardSquare >> downLeft [

	^ self
]

{ #category : 'as yet unclassified' }
MyOffBoardSquare >> downRight [

	^ self
]

{ #category : 'testing' }
MyOffBoardSquare >> hasPiece [

	^ false
]

{ #category : 'testing' }
MyOffBoardSquare >> isOnBoard [

	^ false
]

{ #category : 'accessing' }
MyOffBoardSquare >> left [

	^ self
]

{ #category : 'accessing' }
MyOffBoardSquare >> right [

	^ self
]

{ #category : 'instance creation' }
MyOffBoardSquare >> up [

	^ self
]

{ #category : 'as yet unclassified' }
MyOffBoardSquare >> upLeft [

	^ self
]

{ #category : 'as yet unclassified' }
MyOffBoardSquare >> upRight [

	^ self
]
