"
# Example
```
MyFENParser parse: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1'.
```
"
Class {
	#name : 'MyFENParser',
	#superclass : 'Object',
	#instVars : [
		'stream',
		'pieces'
	],
	#category : 'Myg-Chess-Importers',
	#package : 'Myg-Chess-Importers'
}

{ #category : 'parsing' }
MyFENParser class >> forString: aString [

	^ self new
		  stream: aString readStream;
		  yourself
]

{ #category : 'parsing' }
MyFENParser class >> parse: aString [

	^ (self forString: aString readStream) parse
]

{ #category : 'parsing' }
MyFENParser >> expectString: expectedString [

	| parsedToken |
	parsedToken := stream next: expectedString size.
	self assert: parsedToken = expectedString
]

{ #category : 'initialization' }
MyFENParser >> initialize [
	super initialize.
	pieces := Dictionary new.
	pieces at: $P put: 'White pawn'.
	pieces at: $N put: 'White knight'.
	pieces at: $B put: 'White bishop'.
	pieces at: $R put: 'White rook'.
	pieces at: $Q put: 'White queen'.
	pieces at: $K put: 'White king'.
	
	pieces at: $p put: 'Black pawn'.
	pieces at: $n put: 'Black knight'.
	pieces at: $b put: 'Black bishop'.
	pieces at: $r put: 'Black rook'.
	pieces at: $q put: 'Black queen'.
	pieces at: $k put: 'Black king'.
]

{ #category : 'parsing' }
MyFENParser >> parse [

	| game |
	game := MyFENGame new.

	game ranks: self parseRanks.
	self expectString: ' '.
	game sideToMove: self parseSideToMove.
	self expectString: ' '.
	game castlingAbility: self parseCastlingAbility.
	self expectString: ' '.
	game enPassantTargetSquare: self parseEnPassant.
	self expectString: ' '.
	game halfMoveClock: self parseNumber.
	self expectString: ' '.
	game moveCount: self parseNumber.

	^ game
]

{ #category : 'parsing' }
MyFENParser >> parseAnyOf: options [

	| token |
	token := stream next.
	(options includes: token) ifFalse: [
		self error: 'Expected one of ' , options asString ].
	^ token
]

{ #category : 'parsing' }
MyFENParser >> parseCastlingAbility [

	| rights |
	self peek = $- ifTrue: [
		stream next.
		^ 'NO CASTLING' ].

	rights := OrderedCollection new.
	[ self peek notNil and: [ #( $k $K $q $Q ) includes: self peek ] ]
		whileTrue: [ rights add: stream next ].
	rights ifEmpty: [ self error: 'Expected castling rights' ].
	^ rights
]

{ #category : 'parsing' }
MyFENParser >> parseEnPassant [

	self peek = $- ifTrue: [ 
		self parseAnyOf: #( $- ).
		^ 'NO ENPASSANT' ].
	^ self parseSquare
]

{ #category : 'parsing' }
MyFENParser >> parseNumber [

	| number |
	number := (stream upTo: Character space) asNumber.
	stream atEnd ifFalse: [ stream position: stream position - 1 ].
	^ number
]

{ #category : 'parsing' }
MyFENParser >> parsePiece [
	
	| identifier |
	identifier := stream next.
	^ pieces at: identifier
]

{ #category : 'parsing' }
MyFENParser >> parseRank [

	| rank |
	rank := OrderedCollection new.
	[ self peek notNil and: [ (#( $  $/ ) includes: self peek) not ] ]
		whileTrue: [
			self peek isDigit
				ifTrue: [
					| count |
					count := stream next digitValue.
					(count between: 1 and: 8) ifFalse: [
						self error: 'Invalid number of empty squares' ].
					count timesRepeat: [ rank add: 'empty' ] ]
				ifFalse: [ rank add: self parsePiece ] ].
	rank size = 8 ifFalse: [ self error: 'A rank must have 8 squares' ].
	^ rank
]

{ #category : 'parsing' }
MyFENParser >> parseRanks [

	| ranks |
	ranks := (1 to: 7)
		         collect: [ :i |
			         | rank |
			         rank := self parseRank.
			         self expectString: '/'.
			         rank ]
		         as: OrderedCollection.
	ranks add: self parseRank.
	^ ranks
]

{ #category : 'parsing' }
MyFENParser >> parseSideToMove [

	| sideToMove |
	sideToMove := stream next.
	sideToMove = $b ifTrue: [ ^ 'Black'].
	sideToMove = $w ifTrue: [ ^ 'White'].
	self error: 'Expected side to move'
]

{ #category : 'parsing' }
MyFENParser >> parseSquare [

	^ {
		  (self parseAnyOf: ($a to: $h)).
		  (self parseAnyOf: #( $3 $6 )) }
]

{ #category : 'parsing' }
MyFENParser >> peek [

	^ stream peek
]

{ #category : 'accessing' }
MyFENParser >> stream: aReadStream [ 
	stream := aReadStream
]
